---
title: "Iterations and List Columns"
output: github_document
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load key packages.

```{r}
library(tidyverse)
library(rvest)
```


Set seed for reproducibility.

```{r}
set.seed(12345)
```



### Lists

```{r}
vec_numeric = 1:4
vec_char = c("my", "name", "is", "jeff")

tibble(
  num = vec_numeric,
  char = vec_char
)
```

Different stuff with different lengths

```{r}
l = list(
      vec_numeric = 1:5,
      vec_char = LETTERS,
      matrix = matrix(1:10, nrow = 5, ncol = 2),
      summary = summary(rnorm(100))
    )
```


Accessing lists

```{r}
l$vec_char
l[[1]]
l[["summary"]]
```


### Loops

```{r}
list_norm_samples = 
  list(
    a = rnorm(20, 1, 5),
    b = rnorm(20, 0, 7),
    c = rnorm(20, 20, 1),
    d = rnorm(20, -45, 13)
  )
```

mean and sd function

```{r}
mean_and_sd = function(x) {
  
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

```{r}
mean_and_sd(list_norm_samples$a)
mean_and_sd(list_norm_samples$b)
mean_and_sd(list_norm_samples$c)
mean_and_sd(list_norm_samples$d)
```

Write a `for` loop to do this more efficiently.

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm_samples[[i]])
  
}
```


### Use `map`

```{r}
output_mean_sd = map(list_norm_samples, mean_and_sd)
output_summary = map(list_norm_samples, summary)
```

Same results as for loop, and copy-paste, but much easier!!!





